"""empty message

Revision ID: 111316da35e9
Revises: 4eb779d0e94a
Create Date: 2023-06-20 21:12:41.767964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111316da35e9'
down_revision = '4eb779d0e94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PaqueteDeViaje', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=800),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PaqueteDeViaje', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
