"""empty message

Revision ID: 223846d3f15f
Revises: 
Create Date: 2023-06-12 23:56:48.093655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223846d3f15f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EstatusReservado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Agencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rif', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('Viajero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_person', sa.String(length=120), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('dates_of_birth', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('AgenciaFavorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=False),
    sa.Column('viajero_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agencia_id'], ['Agencia.id'], ),
    sa.ForeignKeyConstraint(['viajero_id'], ['Viajero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PaqueteDeViaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('starting_location', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('finish_date', sa.DateTime(), nullable=False),
    sa.Column('includes', sa.String(length=120), nullable=False),
    sa.Column('type_of_transport', sa.String(length=120), nullable=False),
    sa.Column('type_of_accommodation', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('max_travellers', sa.Integer(), nullable=False),
    sa.Column('reservation_cost', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agencia_id'], ['Agencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ViajeReserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paquetedeviaje_id', sa.Integer(), nullable=False),
    sa.Column('viajero_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paquetedeviaje_id'], ['PaqueteDeViaje.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['EstatusReservado.id'], ),
    sa.ForeignKeyConstraint(['viajero_id'], ['Viajero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ViajeReserva')
    op.drop_table('PaqueteDeViaje')
    op.drop_table('AgenciaFavorito')
    op.drop_table('Viajero')
    op.drop_table('Agencia')
    op.drop_table('User')
    op.drop_table('EstatusReservado')
    # ### end Alembic commands ###
