"""empty message

Revision ID: 353c645338ec
Revises: 8ee8fb784213
Create Date: 2023-06-15 23:01:00.046185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353c645338ec'
down_revision = '8ee8fb784213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Viajero', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Viajero', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
