"""empty message

Revision ID: 4eb779d0e94a
Revises: 85538888b820
Create Date: 2023-06-19 16:42:06.478994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb779d0e94a'
down_revision = '85538888b820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EstatusReservado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_status', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EstatusReservado', schema=None) as batch_op:
        batch_op.drop_column('cod_status')

    # ### end Alembic commands ###
