"""empty message

Revision ID: 85538888b820
Revises: 353c645338ec
Create Date: 2023-06-16 00:45:05.266118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85538888b820'
down_revision = '353c645338ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PaqueteDeViaje', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PaqueteDeViaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
