"""empty message

Revision ID: 99bdff9e015c
Revises: 191c82c0ccb0
Create Date: 2023-06-12 00:57:06.905081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bdff9e015c'
down_revision = '191c82c0ccb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Viaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('finish_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('includes', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('type_of_accommodation', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('reservation_cost', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_cost', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('Viaje_description_key', type_='unique')
        batch_op.drop_constraint('Viaje_destination_key', type_='unique')
        batch_op.drop_constraint('Viaje_location_key', type_='unique')
        batch_op.drop_constraint('Viaje_max_travellers_key', type_='unique')
        batch_op.drop_constraint('Viaje_price_key', type_='unique')
        batch_op.drop_constraint('Viaje_starting_location_key', type_='unique')
        batch_op.drop_constraint('Viaje_title_key', type_='unique')
        batch_op.drop_constraint('Viaje_type_of_transport_key', type_='unique')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Viaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('Viaje_type_of_transport_key', ['type_of_transport'])
        batch_op.create_unique_constraint('Viaje_title_key', ['title'])
        batch_op.create_unique_constraint('Viaje_starting_location_key', ['starting_location'])
        batch_op.create_unique_constraint('Viaje_price_key', ['price'])
        batch_op.create_unique_constraint('Viaje_max_travellers_key', ['max_travellers'])
        batch_op.create_unique_constraint('Viaje_location_key', ['location'])
        batch_op.create_unique_constraint('Viaje_destination_key', ['destination'])
        batch_op.create_unique_constraint('Viaje_description_key', ['description'])
        batch_op.drop_column('creation_date')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('reservation_cost')
        batch_op.drop_column('type_of_accommodation')
        batch_op.drop_column('includes')
        batch_op.drop_column('finish_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
