"""empty message

Revision ID: b28ad27105bd
Revises: 111316da35e9
Create Date: 2023-06-21 01:35:50.351199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28ad27105bd'
down_revision = '111316da35e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ViajeReserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cant_viajeros_reserva', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ViajeReserva', schema=None) as batch_op:
        batch_op.drop_column('cant_viajeros_reserva')

    # ### end Alembic commands ###
